### ISSUE TITLE
Missing build documentation

### ISSUE THREAD

**Issue by xyproto** [msimon/chip8#2]
I'm trying to build chip8. I'm relatively new to OCaml. I could not see any installation or build instructions, so I tried building with `make`:

```
$ make
ocamlbuild -use-ocamlfind src/main.native
Finished, 0 targets (0 cached) in 00:00:00.
+ ocamlfind ocamldep -syntax camlp4o -package lwt,lwt.syntax,lwt.extra -modules src/main.ml > src/main.ml.depends
ocamlfind: Package `lwt.syntax' not found
Command exited with code 2.
Compilation unsuccessful after building 1 target (0 cached) in 00:00:00.
make: *** [all] Error 10
```

I could not find any `lwt.syntax` package by using `opam`.

What are the build/installation instructions for building chip8?

**Comment by msimon** [comment]
Hey Alexander,

New to OCaml? You're missing the camlp4 package.
If you run `opam install camlp4`, it should rebuild Lwt with the Lwt.syntax

I'm very surprise anyone is trying to build this.
Here some more info how to build this:

   - In _tags, replace lwt.extra by lwt.unix (1st line). There was some
   changes in Lwt since I wrote that.
   - Make sure you have SDL install on your system.
   - Once you do: run `opam install ocamlsdl`
   - `Make`


Let me know if you need more help.

Quick question, why are you trying to build this ?

Thanks

**Comment by xyproto** [comment]
Yes, I am relatively new to OCaml. My motivation for building chip8 is to learn more about OCaml and the tooling that surrounds it. I maintain a few packages for Arch Linux and learning how to fix build issues, depending on the language involved, is important in order to package applications.

chip8 builds now, thanks!

Cheers
